timeout: 3
default_entry: 2
interface_branding: NasuaOS

interface_help_hidden: yes

/NasuaOS 32-bit
    protocol: multiboot
    path: boot():/boot/kernel_32bit

/NasuaOS 64-bit
    protocol: limine
    path: boot():/boot/kernel_64bit