timeout: 5
default_entry: NasuaOS 64-bit
interface_branding: NasuaOS

interface_help_hidden: yes

# Debug
verbose: yes

interface_resolution: 1280x720

wallpaper: boot():/boot/assets/images/background.png
wallpaper_style: stretched

/NasuaOS 32-bit
    protocol: multiboot
    path: boot():/boot/kernel_32bit
    textmode: yes
    comment: Basic console-only environment

/NasuaOS 64-bit
    protocol: limine
    path: boot():/boot/kernel_64bit
    resolution: 1280x720
    comment: Full operating system with graphical interface (recommended)