#!/bin/sh

set -e

srcdir="$(dirname "$0")"
test -z "$srcdir" && srcdir=.

cd "$srcdir"

rm -f .deps-obtained

rm -rf temp

git clone --depth 1 \
    --branch main \
    https://github.com/Szatakis/NasuaOS-Bootloader.git \
    temp

cp -r temp/freestanding-c-hdrs .
cp -r temp/freestanding-cxx-hdrs .
cp -r temp/cc-runtime .
cp -r temp/limine-protocol .

rm -rf temp

touch .deps-obtained

printf "\nDependencies obtained successfully.\n"