name: Build NasuaOS

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            gcc \
            g++ \
            cmake \
            xorriso \
            clang \
            lld \
            nasm \
            mtools \
            qemu-system-x86

      - name: Build ISO
        run: |
          make all

      - name: Build HDD image
        run: |
          make all-hdd

      - name: Find images
        run: |
          echo "Generated files:"
          find . \( -name "*.iso" -o -name "*.hdd" \) -type f

      - name: Upload ISO and HDD to iso branch
        run: |
          mkdir release

          cp $(find . -name "*.iso" | head -n 1) release/
          cp $(find . -name "*.hdd" | head -n 1) release/

          cd release

          git init
          git checkout -b iso

          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add .
          git commit -m "Update NasuaOS images"

          git remote add origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          git push --force origin iso